apiVersion: v1
kind: ConfigMap
metadata:
  name: fence-accesslog-source
  namespace: {{ .Release.Namespace }}
data:
  custom_bootstrap.json: |
    {
      "static_resources": {
        "clusters": [{
          "name": "fence-accesslog-source",
          "type": "STRICT_DNS",
          "connect_timeout": "5s",
          "http2_protocol_options": {},
          "dns_lookup_family": "V4_ONLY",
          "load_assignment": {
            "cluster_name": "fence-accesslog-source",
            "endpoints": [{
              "lb_endpoints": [{
                "endpoint": {
                  "address": {
                    "socket_address": {
                      "address": "fence.{{ .Release.Namespace }}",
                      "port_value": {{ .Values.fence.logSourcePort }}
                    }
                  }
                }
              }]
            }]
          },
          "respect_dns_ttl": true
        }]
      }
    }
